// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJeetXfhnSdyHjEBxzO2Ia_IeFYmmwYk',
    appId: '1:131959635436:web:1598935006e65247d6d4c9',
    messagingSenderId: '131959635436',
    projectId: 'crud-mobile-cf872',
    authDomain: 'crud-mobile-cf872.firebaseapp.com',
    storageBucket: 'crud-mobile-cf872.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqIHyVfqschLRXwYRzb316t5ghkuP280',
    appId: '1:131959635436:android:223ff04a365b275dd6d4c9',
    messagingSenderId: '131959635436',
    projectId: 'crud-mobile-cf872',
    storageBucket: 'crud-mobile-cf872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzTXAUaiq7jxaOlMPYvHb5WPhvCbEZOU',
    appId: '1:131959635436:ios:2e35c15fd8aa545cd6d4c9',
    messagingSenderId: '131959635436',
    projectId: 'crud-mobile-cf872',
    storageBucket: 'crud-mobile-cf872.firebasestorage.app',
    iosBundleId: 'com.example.latihanCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjzTXAUaiq7jxaOlMPYvHb5WPhvCbEZOU',
    appId: '1:131959635436:ios:2e35c15fd8aa545cd6d4c9',
    messagingSenderId: '131959635436',
    projectId: 'crud-mobile-cf872',
    storageBucket: 'crud-mobile-cf872.firebasestorage.app',
    iosBundleId: 'com.example.latihanCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJeetXfhnSdyHjEBxzO2Ia_IeFYmmwYk',
    appId: '1:131959635436:web:7c376d93834fc703d6d4c9',
    messagingSenderId: '131959635436',
    projectId: 'crud-mobile-cf872',
    authDomain: 'crud-mobile-cf872.firebaseapp.com',
    storageBucket: 'crud-mobile-cf872.firebasestorage.app',
  );
}
